#define WIFI_SSID "<YOUR_SSID>"
#define WIFI_PASSWORD "<YOUR_WIFI_PASSWORD>"
#define MQTT_SERVER_HOST "<YOUR_MQTT_SERVER_IP>"
#define MQTT_SERVER_PORT 1883
#define MQTT_USER "<YOUR_MQTT_USER>"
#define MQTT_PASS "<YOUR_MQTT_PASS>"