name: Host Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc     
          ninjaVersion: latest

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Create build directory
        run: mkdir -p build
          
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DON_TARGET=OFF

      - name: Build with CMake
        run: cmake --build build --config Release
  test:
    steps:
      - name: Run tests
        run: cd build/test && ctest --output-on-failure
